openapi: 3.0.0
info:
  title: Role Assignment API
  version: 1.0.0
  description: API for assigning roles to users.

paths:
  /api/roles/assign-role:
    post:
      summary: Assign a role to a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - roleName
              properties:
                userId:
                  type: string
                  example: "user123"
                roleName:
                  type: string
                  example: "Admin"
      responses:
        201:
          description: Role assigned successfully
        400:
          description: Missing required fields
        500:
          description: Server error
